services:
  web:
    image: synthetic:data
    build:
      context: .
    command: uvicorn synthetic.asgi:application --host '0.0.0.0' --reload
    ports:
      - 8000:8000
    volumes:
      - .:/app